### ISSUE TITLE
SteamDeck адаптация для программы Discover (KDE)

### ISSUE THREAD

**Issue by alexeik** [DeusExMachinaTeam/EM-CommunityPatch#497]
Может , ктото написать инструкцию, как сделать пакет и перенести на SteamDeck уже готовую сборку?
Коненчо ясно, что на винде можно сделать и перенести потом.
ВОзможно более красиво это делается.

**Comment by DeusExMachinaTeam** [comment]
Существует бранч мод менеджера ComMod адаптированный для запуске на Linux, можно пока воспользоваться им:
https://github.com/Zvetkov/ComMod/pull/5

**Comment by alexeik** [comment]
А в Dicsovery STore от KDE будете отправлять, чтобы кнопочкой установить  на СтимеДеке?

**Comment by stele95** [comment]
I managed to install this mod on my Linux PC for the Steam version of the game by using a Windows installation inside the Virtual Machine since I don't have a Windows PC:
- Installed HTA/EM on a Linux PC and switched to Russian version
- Installed HTA/EM in a Windows VM and switched to Russian version.
- In the Windows VM, installed the mod through ComMod
- Zipped the whole game folder and copied to the Linux PC
- Extracted the files in the game folder on the Linux PC

So far it seems to be working fine, but I haven't played for too long

**Comment by DeusExMachinaTeam** [comment]
ComMod now has native Linux support and binary builds [starting with 2.2 release](https://github.com/Zvetkov/ComMod/releases). Distribution via Discover or similar platforms is not being planned at this point as it's had to evaluate how useful that will be for our users. You can share your experiences and requests in our Discord.

У ComMod теперь есть нативная поддержка Linux и бинарный релиз, [начиная с версии 2.2](https://github.com/Zvetkov/ComMod/releases). Распространение через Discover или подобные платформу пока не планируется всвязи с непонятным спросом на данное решение. Оставляйте свои отзывы и запросы у нас в Discord.
